version: "3.3"
services:
  front:
    image: python:3.11-alpine
    build:
      context: ../../Downloads
      dockerfile: Dockerfile
    ports:
      - "3000:5000"

  db:
    image: postgres:15
    restart: always
    ports:
      - "5431:5432"
    environment:
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=bdproyecto
